""" secret stuff"""
import sys
def android():
    """android ASCII art"""
    sys.stdout.write("\t             I                I             ")
    sys.stdout.write("\t              I      ++      I              ")
    sys.stdout.write("\t               IIIIIIIIIIIIII               ")
    sys.stdout.write("\t             IIIIIIIIIIIIIIIIII             ")
    sys.stdout.write("\t           IIIIIIIIIIIIIIIIIIIIII           ")
    sys.stdout.write("\t         IIII   IIIIIIIIIIII   IIII         ")
    sys.stdout.write("\t        IIIIIIIIIIIIIIIIIIIIIIIIIIII        ")
    sys.stdout.write("\t       IIIIIIIIIIIIIIIIIIIIIIIIIIIIII       ")
    sys.stdout.write("\t       IIIIIIIIIIIIIIIIIIIIIIIIIIIIII       ")
    sys.stdout.write("\t       IIIIIIIIIIIIIIIIIIIIIIIIIIIIII       ")
    sys.stdout.write("\t IIII  IIIIIIIIIIIIIIIIIIIIIIIIIIIIII  IIII ")
    sys.stdout.write("\tIIIIII IIIIIIIIIIIIIIIIIIIIIIIIIIIIII IIIIII")
    sys.stdout.write("\tIIIIII IIIIIIIIIIIIIIIIIIIIIIIIIIIIII IIIIII")
    sys.stdout.write("\tIIIIII IIIIIIIIIIIIIIIIIIIIIIIIIIIIII IIIIII")
    sys.stdout.write("\tIIIIII IIIIIIIIIIIIIIIIIIIIIIIIIIIIII IIIIII")
    sys.stdout.write("\tIIIIII IIIIIIIIIIIIIIIIIIIIIIIIIIIIII IIIIII")
    sys.stdout.write("\tIIIIII IIIIIIIIIIIIIIIIIIIIIIIIIIIIII IIIIII")
    sys.stdout.write("\tIIIIII IIIIIIIIIIIIIIIIIIIIIIIIIIIIII IIIIII")
    sys.stdout.write("\tIIIIII IIIIIIIIIIIIIIIIIIIIIIIIIIIIII IIIIII")
    sys.stdout.write("\tIIIIII IIIIIIIIIIIIIIIIIIIIIIIIIIIIII IIIIII")
    sys.stdout.write("\tIIIIII IIIIIIIIIIIIIIIIIIIIIIIIIIIIII IIIIII")
    sys.stdout.write("\tIIIIII IIIIIIIIIIIIIIIIIIIIIIIIIIIIII IIIIII")
    sys.stdout.write("\t+IIII  IIIIIIIIIIIIIIIIIIIIIIIIIIIIII  IIII:")
    sys.stdout.write("\t       IIIIIIIIIIIIIIIIIIIIIIIIIIIIII       ")
    sys.stdout.write("\t        IIIIIIIIIIIIIIIIIIIIIIIIIIII        ")
    sys.stdout.write("\t             IIIIII      IIIIII             ")
    sys.stdout.write("\t             IIIIII      IIIIII             ")
    sys.stdout.write("\t             IIIIII      IIIIII             ")
    sys.stdout.write("\t             IIIIII      IIIIII             ")
    sys.stdout.write("\t             IIIIII      IIIIII             ")
    sys.stdout.write("\t               I:          ~I               ")
